# Generated by Django 3.2.10 on 2022-03-09 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=215)),
                ('status', models.IntegerField(choices=[(1, 'Not Booked'), (2, 'Ready For Booking'), (3, 'Booking on '), (4, 'Booking over')], default=1)),
                ('max_seats', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ListEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start', models.DateTimeField(default=None)),
                ('booking_end', models.DateTimeField(default=None)),
                ('price_per_seat', models.IntegerField(default=100)),
                ('seats_avaialble', models.IntegerField(default=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventrr.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats_booked', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('ListEvents', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventrr.listevents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ListEvents', 'user')},
            },
        ),
    ]
