# Generated by Django 3.2.12 on 2022-03-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventrr', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_name', 'desc')},
        ),
    ]
