# Generated by Django 3.2.12 on 2022-03-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventrr', '0002_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventrr.event', unique=True),
        ),
    ]
